dist: xenial

language: python

python:
  - 3.8
  - 3.7
  - 3.6
arch:
  - amd64
  - ppc64le
env:
  - DJANGO="Django>=3.2,<3.3"
  - DJANGO="Django>=3.1,<3.2"
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.0,<2.1"

install:
  - pip install -U coverage coveralls $DJANGO

script: coverage run -a --source=sitetree setup.py test

after_success:
  coveralls
